language: python
sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/matplotlib

python:
  - 2.7
  - 3.5
  - 3.6

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/mc
  - export PATH=~/mc/bin:$PATH
  - conda config --add channels conda-forge
  - conda config --set always_yes yes --set changeps1 no --set quiet true
  - conda update conda --yes

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes --file requirements/build.txt
  - conda install pip
  - pip install -r requirements/pip.txt
  - python setup.py install
  - git clean -xfd

script:
  - set -e
  - conda install --yes --file requirements/run.txt
  - conda install --yes --file requirements/test.txt
  - coverage run run_tests.py
  - coverage report -m
  - codecov
  - |
    if [ $TRAVIS_PYTHON_VERSION = "3.6" ]; then
      conda install --yes --file requirements/docs.txt
      cd doc
      make html
      cd ..
      doctr deploy . --built-docs ./docs/_build/html;
    fi

after_script:
  - set +e
  - flake8 diffpy
